export const WEATHER_TYPES = {
    GET_LOCATION_WEATHER:"GET_LOCATION_WEATHER",
    GET_SEARCHED_LOCATION_WEATHER:"GET_SEARCHED_LOCATION_WEATHER",
    SET_PREVIOUS_DATA:" SET_PREVIOUS_DATA",
   
}

export const THEME_TYPES={
    SET_LIGHT_MODE:"SET_LIGHT_MODE",
    SET_DARK_MODE:"SET_DARK_MODE",
}